#!/usr/bin/env python3
"""
Modular Planter System - Customizer
Batch generate STL files with different parameters
"""

import subprocess
import sys
from pathlib import Path

# Preset configurations
PRESETS = {
    "small": {
        "hex_size": 40,
        "height": 60,
        "wall_thickness": 2,
        "desc": "Small herb planter"
    },
    "medium": {
        "hex_size": 60,
        "height": 80,
        "wall_thickness": 2,
        "desc": "Medium succulent planter"
    },
    "large": {
        "hex_size": 80,
        "height": 100,
        "wall_thickness": 2.5,
        "desc": "Large plant planter"
    },
    "shallow": {
        "hex_size": 60,
        "height": 40,
        "wall_thickness": 2,
        "desc": "Shallow tray for cacti"
    },
    "tall": {
        "hex_size": 50,
        "height": 120,
        "wall_thickness": 2,
        "desc": "Tall for deep-rooted plants"
    }
}

def generate_openscad(preset_name, params, output_dir):
    """Generate OpenSCAD file with specific parameters"""
    
    scad_content = f'''// Modular Planter - {preset_name.title()} ({params['desc']})
// Generated by customizer.py

// Parameters
hex_size = {params['hex_size']};
height = {params['height']};
wall_thickness = {params['wall_thickness']};
bottom_thickness = 3;
drainage_hole_d = 5;
connector_depth = 5;
connector_tolerance = 0.3;

// Derived values
apothem = hex_size * sqrt(3) / 2;
inner_apothem = apothem - wall_thickness;

// Main planter module
module planter_module() {{
    difference() {{
        linear_extrude(height = height)
            hexagon(apothem);
        
        translate([0, 0, bottom_thickness])
            linear_extrude(height = height - bottom_thickness + 1)
                hexagon(inner_apothem);
        
        for (i = [0:2]) {{
            rotate([0, 0, i * 120])
                translate([inner_apothem * 0.5, 0, -1])
                    cylinder(d = drainage_hole_d, h = bottom_thickness + 2, $fn=20);
        }}
    }}
    
    for (i = [0:2]) {{
        rotate([0, 0, i * 120 + 60])
            translate([apothem - 0.5, 0, height * 0.5])
                connector_male();
    }}
}}

module hexagon(r) {{
    circle(r = r / cos(30), $fn = 6);
}}

module connector_male() {{
    difference() {{
        cube([connector_depth * 2, 8, 6], center = true);
        translate([connector_depth, 0, 0])
            rotate([0, 45, 0])
                cube([6, 10, 6], center = true);
    }}
}}

planter_module();
'''
    
    output_file = output_dir / f"planter-{preset_name}.scad"
    output_file.write_text(scad_content)
    print(f"Generated: {output_file}")
    return output_file

def export_stl(scad_file, output_dir):
    """Export SCAD to STL using OpenSCAD"""
    stl_file = output_dir / (scad_file.stem + ".stl")
    
    try:
        subprocess.run([
            "openscad",
            "-o", str(stl_file),
            str(scad_file)
        ], check=True)
        print(f"Exported: {stl_file}")
        return True
    except subprocess.CalledProcessError:
        print(f"Failed to export: {scad_file.name}")
        return False
    except FileNotFoundError:
        print("WARNING: OpenSCAD not found. Install from openscad.org")
        print(f"  You can manually open: {scad_file}")
        return False

def main():
    """Main entry point"""
    print("Modular Planter System - Customizer")
    print("=" * 40)
    
    # Create output directory
    output_dir = Path("generated")
    output_dir.mkdir(exist_ok=True)
    
    # Generate all presets
    for preset_name, params in PRESETS.items():
        print(f"\nGenerating: {preset_name.title()} ({params['desc']})")
        scad_file = generate_openscad(preset_name, params, output_dir)
        
        # Try to export to STL if OpenSCAD is installed
        export_stl(scad_file, output_dir)
    
    print(f"\nDone! Files saved to: {output_dir.absolute()}")
    print("\nTo export STL files:")
    print("1. Install OpenSCAD from https://openscad.org")
    print("2. Run: python customizer.py")
    print("3. Or open .scad files in OpenSCAD and export manually")

if __name__ == "__main__":
    main()
